name: Generate Snake Game from GitHub Contribution Grid

on:
  # Run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # Run on every push to main branch
  push:
    branches: [ main ]

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          # github user name to read the contribution graph from (**required**)
          # using action context var `github.repository_owner` or specified user
          github_user_name: ${{ github.repository_owner }}
          
          # list of files to generate.
          # one file per line. Each output can be customized with options as query string.
          #
          # supported options:
          # - palette:     A preset of color, one of [github, github-dark, github-light]
          # - color_snake: Color of the snake
          # - color_dots:  Coma separated list of colors for the dots
          outputs: |
            snake.svg?palette=github-light&color_snake=orange
            snake-dark.svg?palette=github-dark&color_snake=orange
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
      
      # Push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}